export const industriesMetadata = [
  {
    slug: 'mineria',
    name: 'Minería',
    title: 'Guardias de Seguridad para Minería en Chile | Gard Security',
    description: 'Protección especializada 24/7 para mineras. Personal certificado OS10, monitoreo remoto y respuesta inmediata. +15 años protegiendo operaciones mineras. Cotice aquí.',
    keywords: ['guardias seguridad minería', 'seguridad minera chile', 'guardias certificados OS10', 'seguridad industrial minería', 'protección faenas mineras'],
  },
  {
    slug: 'retail',
    name: 'Retail',
    title: 'Guardias para Retail y Centros Comerciales | Gard Security',
    description: 'Guardias capacitados para el control de accesos, vigilancia y prevención de pérdidas en tiendas y malls.',
    keywords: ['guardias para retail', 'seguridad en centros comerciales', 'prevención de pérdidas'],
  },
  {
    slug: 'salud',
    name: 'Salud',
    title: 'Seguridad para Instituciones de Salud | Gard Security',
    description: 'Guardias con protocolos para hospitales, clínicas y centros médicos. Control de acceso y gestión de visitantes.',
    keywords: ['seguridad en salud', 'guardias para clínicas', 'hospitales seguros'],
  },
  {
    slug: 'infraestructura-critica',
    name: 'Infraestructura Crítica',
    title: 'Seguridad en Infraestructura Crítica | Gard Security',
    description: 'Protección de instalaciones estratégicas con protocolos especiales, monitoreo constante y personal altamente calificado.',
    keywords: ['seguridad infraestructura crítica', 'guardias estratégicos', 'protección de activos'],
  },
  {
    slug: 'educacion',
    name: 'Educación',
    title: 'Guardias para Colegios y Universidades | Gard Security',
    description: 'Control de acceso seguro, monitoreo perimetral y guardias entrenados para espacios educacionales.',
    keywords: ['seguridad colegios', 'guardias para universidades', 'seguridad educacional'],
  },
  {
    slug: 'eventos-y-espectaculos',
    name: 'Eventos y Espectáculos',
    title: 'Seguridad para Eventos y Espectáculos | Gard Security',
    description: 'Guardias de seguridad y control de acceso para eventos, conciertos y espectáculos masivos.',
    keywords: ['seguridad eventos', 'guardias conciertos', 'control de multitudes'],
  },
  {
    slug: 'bodegas',
    name: 'Bodegas',
    title: 'Seguridad para Bodegas Logísticas Chile | Guardias 24/7',
    description: 'Protección integral de inventario y mercancía. Guardias especializados, control de acceso biométrico y CCTV. Reducimos mermas hasta 85%. Cotización inmediata.',
    keywords: ['seguridad bodegas chile', 'guardias almacenes logística', 'protección inventario', 'vigilancia centros distribución', 'seguridad bodega 24/7'],
  },
  {
    slug: 'edificios-corporativos',
    name: 'Edificios Corporativos',
    title: 'Guardias para Edificios Corporativos Santiago | Gard Security',
    description: 'Seguridad profesional para edificios de oficinas. Control de acceso inteligente, recepción 24/7 y protocolo ejecutivo. +50 edificios protegidos en Santiago. Cotice ahora.',
    keywords: ['guardias edificios corporativos', 'seguridad oficinas santiago', 'control acceso edificios', 'recepción corporativa', 'seguridad empresarial chile'],
  },
  {
    slug: 'construccion',
    name: 'Construcción',
    title: 'Seguridad para Obras de Construcción Chile | Guardias 24/7',
    description: 'Protección de faenas y maquinaria. Guardias especializados en construcción, control de ingreso y rondas nocturnas. Evite robos y vandalismo. Cotice seguridad para su obra.',
    keywords: ['seguridad construcción chile', 'guardias obras', 'protección maquinaria construcción', 'vigilancia faenas', 'seguridad obras 24/7'],
  },
  {
    slug: 'transporte-y-logistica',
    name: 'Transporte y Logística',
    title: 'Guardias de Seguridad para Transporte y Logística Chile',
    description: 'Protección de flotas, terminales y carga en tránsito. Guardias especializados, GPS tracking y escoltas. Cobertura nacional. Cotice seguridad para su operación logística.',
    keywords: ['seguridad transporte chile', 'guardias logística', 'protección carga', 'escoltas transporte', 'seguridad terminales logísticos', 'vigilancia flotas'],
  },
  {
    slug: 'parques-industriales',
    name: 'Parques Industriales',
    title: 'Seguridad para Parques Industriales Chile | Gard Security',
    description: 'Vigilancia perimetral avanzada para parques industriales. Drones, CCTV perimetral y guardias especializados. Protección multi-empresa. Cotice seguridad integral para su parque.',
    keywords: ['seguridad parques industriales chile', 'vigilancia perimetral industrial', 'guardias parques', 'control acceso industrial', 'seguridad zonas industriales'],
  },
  {
    slug: 'instituciones-publicas',
    name: 'Instituciones Públicas',
    title: 'Seguridad para Instituciones Públicas | Gard Security',
    description: 'Guardias especializados y control de acceso para entidades gubernamentales y edificios públicos.',
    keywords: ['seguridad gubernamental', 'vigilancia edificios públicos', 'control de acceso'],
  },
  {
    slug: 'hoteleria-y-turismo',
    name: 'Hotelería y Turismo',
    title: 'Seguridad para Hotelería y Turismo | Gard Security',
    description: 'Guardias y vigilancia discreta para hoteles, resorts y atracciones turísticas.',
    keywords: ['seguridad hoteles', 'vigilancia turística', 'protección hotelera'],
  },
  {
    slug: 'sector-financiero',
    name: 'Sector Financiero',
    title: 'Seguridad para el Sector Financiero | Gard Security',
    description: 'Protección especializada para bancos, cajas de ahorro y entidades financieras con estrictos protocolos.',
    keywords: ['seguridad bancaria', 'vigilancia cajeros', 'protección bancos'],
  },
  {
    slug: 'agroindustria',
    name: 'Agroindustria',
    title: 'Seguridad para Agroindustria | Gard Security',
    description: 'Vigilancia y control para fundos, plantaciones y procesos agroindustriales en áreas extensas.',
    keywords: ['seguridad agrícola', 'vigilancia rural', 'protección plantaciones'],
  },
  {
    slug: 'centros-comerciales',
    name: 'Centros Comerciales',
    title: 'Seguridad para Centros Comerciales | Gard Security',
    description: 'Vigilancia, control de acceso y gestión de emergencias para malls y centros comerciales.',
    keywords: ['seguridad malls', 'vigilancia centros comerciales', 'control de multitudes'],
  },
  {
    slug: 'manufactura',
    name: 'Manufactura',
    title: 'Seguridad Industrial para Plantas de Manufactura Chile',
    description: 'Guardias especializados para plantas productivas. Control de acceso, vigilancia de procesos y protección de activos. Cumplimiento normativo garantizado. Cotice seguridad industrial.',
    keywords: ['seguridad manufactura chile', 'guardias plantas industriales', 'seguridad industrial', 'protección fábricas', 'vigilancia plantas producción'],
  },
  {
    slug: 'condominios-residenciales',
    name: 'Condominios Residenciales',
    title: 'Seguridad para Condominios Residenciales | Gard Security',
    description: 'Guardias, control de acceso y monitoreo para condominios y comunidades residenciales.',
    keywords: ['seguridad condominios', 'vigilancia residencial', 'control acceso'],
  },
  {
    slug: 'centros-de-datos',
    name: 'Centros de Datos',
    title: 'Seguridad para Centros de Datos | Gard Security',
    description: 'Protección de infraestructura crítica para data centers y centros de procesamiento de datos.',
    keywords: ['seguridad data center', 'protección TI', 'acceso controlado'],
  },
  {
    slug: 'puertos-terminales',
    name: 'Puertos y Terminales',
    title: 'Seguridad para Puertos y Terminales | Gard Security',
    description: 'Vigilancia especializada para puertos, terminales marítimas y operaciones portuarias.',
    keywords: ['seguridad portuaria', 'vigilancia terminales', 'control acceso puertos'],
  },
  {
    slug: 'sector-energetico',
    name: 'Sector Energético',
    title: 'Seguridad para Sector Energético Chile | Plantas Solares y Eólicas',
    description: 'Protección especializada para infraestructura energética crítica. Vigilancia con drones, monitoreo remoto 24/7 y respuesta ante emergencias. Cotice seguridad para su planta.',
    keywords: ['seguridad sector energético chile', 'vigilancia plantas solares', 'seguridad parques eólicos', 'protección infraestructura energética', 'guardias energía'],
  },
  {
    slug: 'farmaceutica',
    name: 'Industria Farmacéutica',
    title: 'Seguridad para la Industria Farmacéutica | Gard Security',
    description: 'Vigilancia especializada para laboratorios, plantas de producción y distribución farmacéutica.',
    keywords: ['seguridad farmacéutica', 'vigilancia laboratorios', 'control acceso'],
  },
  {
    slug: 'instalaciones-deportivas',
    name: 'Instalaciones Deportivas',
    title: 'Seguridad para Instalaciones Deportivas | Gard Security',
    description: 'Guardias, control de acceso y gestión de eventos para estadios, complejos deportivos y recintos.',
    keywords: ['seguridad estadios', 'vigilancia eventos deportivos', 'control de multitudes'],
  }
]; 