export const industriesMetadata = [
  {
    slug: 'mineria',
    title: 'Seguridad para la Industria Minera | Gard Security',
    description: 'Soluciones de seguridad privada para faenas mineras, con cobertura 24/7, control de acceso y supervisión en zonas remotas.',
    keywords: ['seguridad minera', 'guardias minería', 'seguridad industrial'],
  },
  {
    slug: 'retail',
    title: 'Guardias para Retail y Centros Comerciales | Gard Security',
    description: 'Guardias capacitados para el control de accesos, vigilancia y prevención de pérdidas en tiendas y malls.',
    keywords: ['guardias para retail', 'seguridad en centros comerciales', 'prevención de pérdidas'],
  },
  {
    slug: 'salud',
    title: 'Seguridad para Instituciones de Salud | Gard Security',
    description: 'Guardias con protocolos para hospitales, clínicas y centros médicos. Control de acceso y gestión de visitantes.',
    keywords: ['seguridad en salud', 'guardias para clínicas', 'hospitales seguros'],
  },
  {
    slug: 'infraestructura-critica',
    title: 'Seguridad en Infraestructura Crítica | Gard Security',
    description: 'Protección de instalaciones estratégicas con protocolos especiales, monitoreo constante y personal altamente calificado.',
    keywords: ['seguridad infraestructura crítica', 'guardias estratégicos', 'protección de activos'],
  },
  {
    slug: 'educacion',
    title: 'Guardias para Colegios y Universidades | Gard Security',
    description: 'Control de acceso seguro, monitoreo perimetral y guardias entrenados para espacios educacionales.',
    keywords: ['seguridad colegios', 'guardias para universidades', 'seguridad educacional'],
  },
  {
    slug: 'eventos-y-espectaculos',
    title: 'Seguridad para Eventos y Espectáculos | Gard Security',
    description: 'Guardias de seguridad y control de acceso para eventos, conciertos y espectáculos masivos.',
    keywords: ['seguridad eventos', 'guardias conciertos', 'control de multitudes'],
  },
  {
    slug: 'bodegas',
    title: 'Seguridad para Bodegas y Almacenes | Gard Security',
    description: 'Protección de inventario, control de acceso y vigilancia 24/7 para bodegas y centros de distribución.',
    keywords: ['seguridad bodegas', 'vigilancia almacenes', 'protección de inventario'],
  },
  {
    slug: 'edificios-corporativos',
    title: 'Seguridad para Edificios Corporativos | Gard Security',
    description: 'Guardias, control de acceso y monitoreo para edificios de oficinas y sedes corporativas.',
    keywords: ['seguridad oficinas', 'control acceso edificios', 'protección empresarial'],
  },
  {
    slug: 'construccion',
    title: 'Seguridad para Construcción | Gard Security',
    description: 'Vigilancia y control de acceso para obras de construcción, protección de maquinaria y materiales.',
    keywords: ['seguridad construcción', 'vigilancia obras', 'protección maquinaria'],
  },
  {
    slug: 'transporte-y-logistica',
    title: 'Seguridad para Transporte y Logística | Gard Security',
    description: 'Protección para flotas, terminales y operaciones logísticas con control de activos en movimiento.',
    keywords: ['seguridad transporte', 'vigilancia logística', 'protección de carga'],
  },
  {
    slug: 'parques-industriales',
    title: 'Seguridad para Parques Industriales | Gard Security',
    description: 'Vigilancia perimetral, control de accesos y monitoreo para parques y zonas industriales.',
    keywords: ['seguridad parques industriales', 'vigilancia industrial', 'control de accesos'],
  },
  {
    slug: 'instituciones-publicas',
    title: 'Seguridad para Instituciones Públicas | Gard Security',
    description: 'Guardias especializados y control de acceso para entidades gubernamentales y edificios públicos.',
    keywords: ['seguridad gubernamental', 'vigilancia edificios públicos', 'control de acceso'],
  },
  {
    slug: 'hoteleria-y-turismo',
    title: 'Seguridad para Hotelería y Turismo | Gard Security',
    description: 'Guardias y vigilancia discreta para hoteles, resorts y atracciones turísticas.',
    keywords: ['seguridad hoteles', 'vigilancia turística', 'protección hotelera'],
  },
  {
    slug: 'sector-financiero',
    title: 'Seguridad para el Sector Financiero | Gard Security',
    description: 'Protección especializada para bancos, cajas de ahorro y entidades financieras con estrictos protocolos.',
    keywords: ['seguridad bancaria', 'vigilancia cajeros', 'protección bancos'],
  },
  {
    slug: 'agroindustria',
    title: 'Seguridad para Agroindustria | Gard Security',
    description: 'Vigilancia y control para fundos, plantaciones y procesos agroindustriales en áreas extensas.',
    keywords: ['seguridad agrícola', 'vigilancia rural', 'protección plantaciones'],
  },
  {
    slug: 'centros-comerciales',
    title: 'Seguridad para Centros Comerciales | Gard Security',
    description: 'Vigilancia, control de acceso y gestión de emergencias para malls y centros comerciales.',
    keywords: ['seguridad malls', 'vigilancia centros comerciales', 'control de multitudes'],
  },
  {
    slug: 'manufactura',
    title: 'Seguridad para Manufactura | Gard Security',
    description: 'Protección para plantas de producción, control de acceso y monitoreo de instalaciones industriales.',
    keywords: ['seguridad industrial', 'vigilancia plantas', 'protección fábricas'],
  },
  {
    slug: 'condominios-residenciales',
    title: 'Seguridad para Condominios Residenciales | Gard Security',
    description: 'Guardias, control de acceso y monitoreo para condominios y comunidades residenciales.',
    keywords: ['seguridad condominios', 'vigilancia residencial', 'control acceso'],
  },
  {
    slug: 'centros-de-datos',
    title: 'Seguridad para Centros de Datos | Gard Security',
    description: 'Protección de infraestructura crítica para data centers y centros de procesamiento de datos.',
    keywords: ['seguridad data center', 'protección TI', 'acceso controlado'],
  },
  {
    slug: 'puertos-terminales',
    title: 'Seguridad para Puertos y Terminales | Gard Security',
    description: 'Vigilancia especializada para puertos, terminales marítimas y operaciones portuarias.',
    keywords: ['seguridad portuaria', 'vigilancia terminales', 'control acceso puertos'],
  },
  {
    slug: 'sector-energetico',
    title: 'Seguridad para el Sector Energético | Gard Security',
    description: 'Protección para plantas eléctricas, instalaciones solares, eólicas y distribución energética.',
    keywords: ['seguridad energética', 'vigilancia plantas', 'protección infraestructura'],
  },
  {
    slug: 'farmaceutica',
    title: 'Seguridad para la Industria Farmacéutica | Gard Security',
    description: 'Vigilancia especializada para laboratorios, plantas de producción y distribución farmacéutica.',
    keywords: ['seguridad farmacéutica', 'vigilancia laboratorios', 'control acceso'],
  },
  {
    slug: 'instalaciones-deportivas',
    title: 'Seguridad para Instalaciones Deportivas | Gard Security',
    description: 'Guardias, control de acceso y gestión de eventos para estadios, complejos deportivos y recintos.',
    keywords: ['seguridad estadios', 'vigilancia eventos deportivos', 'control de multitudes'],
  }
]; 